#
# Module manifest for module 'NewManifest'
#
# Generated by: Tore Grøneng @toregroneng tore@firstpoint.no
#
# Generated on: 18.08.2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CliMenu.psm1'

# Version number of this module.
ModuleVersion = '1.0.52.0'

# ID used to uniquely identify this module
GUID = 'cf5f7609-0631-472e-8617-19f58a2adef4'

# Author of this module
Author = 'Tore Grøneng @toregroneng tore@firstpoint.no'

# Company or vendor of this module
CompanyName = 'Firstpoint AS'

# Copyright statement for this module
Copyright = '(c) 2015 Tore Grøneng @toregroneng tore@firstpoint.no'

# Description of the functionality provided by this module
Description = 'Easily build and edit CLI menus in Powershell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Add-MenuItem', 'Get-Menu', 'Get-MenuItem', 'Get-MenuOption', 'New-Menu', 
               'New-MenuItem', 'Set-MenuOption', 'Show-Menu'

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Menu','Cli','Sub-Menu','Main-Menu','Show-Command','Console','Menus','Main','Sub','User','Menu'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/torgro/cliMenu'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

